name: Dynamite
image: dynamite.png
playerSpeed: 1.5
bulletSpeed: 1.5
reloadTime: 0.1
bulletDamage: 1
playerHp: 7
regenOnKill: 7
grappleCooldown: 1
bulletRange: 15
bulletSpray: 1.2
freezeArrow: true
freezeDuration: 3
arrowRange: 6
abilityCooldown: 5
rocketBarrage: true
rocketDamage: 3
rocketRadius: 2
