name: Dynamike
image: dynamite.png
playerSpeed: 1.2
bulletSpeed: 2.5
reloadTime: 0.1
bulletDamage: 1
bulletRange: 15
sprayAngle: 1.2
playerHp: 7
regenOnKill: 5
grappleCooldown: 3
freezeArrow: true
freezeDuration: 30
freezeRange: 6
freezeSpeed: 3
freezeRadius: 1.5
abilityCooldown: 5
rocketCount: 5
rocketDamage: 3
rocketRadius: 2
rocketDelay: 15
rocketInterval: 10
rocketSpread: 1
