name: Primo
image: primo.png
playerSpeed: 1.0
bulletSpeed: 2
reloadTime: 0.4
grappleSpeed: 2
grappleRange: 10
bulletDamage: 2
playerHp: 15
regenOnKill: 10
grappleCooldown: 3
abilityCooldown: 5
abilityDamage: 1
abilityRange: 5
bulletRange: 4
bulletSize: 8
bulletColor: orange
jump: true
aoeDamage: 5
aoeRadius: 2
aoeHits: 3
flameCone: true
flameDuration: 3
flameInterval: 10
flameColor: rgba(255,128,0,0.4)
flameAngle: 1
flameRange: 6
